<?php
// $Id$

/**
 * @file 
 * Allows operations to be performed on items selected in a view.
 */

/**
 * Implementation of hook_views_api().
 */
function fullcalendar_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
 * Implementation of hook_init().
 */
function fullcalendar_init() {
}

function template_preprocess_fullcalendar_view(&$vars) {
  drupal_add_css(drupal_get_path('module', 'fullcalendar') .'/fullcalendar.css');
  drupal_add_js(drupal_get_path('module', 'fullcalendar') .'/fullcalendar.js');
  drupal_add_js(drupal_get_path('module', 'fullcalendar') .'/fullcalendar_views.js');
  jquery_ui_add(array('ui.draggable', 'ui.droppable', 'ui.resizable'));

  $rows = array();//(array)$vars['rows'];
  foreach($vars['rows'] as $id => $row) {
//    $rows[] = $row;
  }
  $vars['rows'] = $rows;
  template_preprocess_views_view_unformatted($vars);
}
